#define IDC_control_ListItem L"control_ListItem"
#define IDC_control_ListItem L"control_ListItem"
#define IDC_control_ListItem L"control_ListItem"
#define IDC_HowToListButtons L"HowToListButtons"
#define IDC_SceneHowToPlayMenu L"SceneHowToPlayMenu"
