copy ErrorPS3Strings.xml de-DE
copy ErrorPS3Strings.xml es-ES
copy ErrorPS3Strings.xml fr-FR
copy ErrorPS3Strings.xml it-IT
copy ErrorPS3Strings.xml ja-JP
copy ErrorPS3Strings.xml ko-KR
copy ErrorPS3Strings.xml pt-BR
copy ErrorPS3Strings.xml pt-PT
copy ErrorPS3Strings.xml ru-RU
copy ErrorPS3Strings.xml zh-CHT